### ISSUE TITLE
there is no wifi here

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/HelloCityScience#1]
cannot use github

**Comment by doorleyr** [comment]
Cannot recreate the issue. I have wifi. Closing this issue.

**Comment by SutaBeacon** [comment]
I can fix it.

**Comment by hlgrprng** [comment]
we have the same problem

**Comment by yasushisakai** [comment]
were are you @SutaBeacon

**Comment by SutaBeacon** [comment]
[Wi-Fi Connection.pdf](https://github.com/CityScope/HelloCityScience/files/2021709/Wi-Fi.Connection.pdf)
Please check this file to connect again.
