### ISSUE TITLE
 have a great idea, lets use spaces on Living line in more systemic way, as a network!

### ISSUE THREAD

**Issue by jarm0s** [CityScope/HelloCityScience#2]
have a great idea, lets use spaces on Living line in more systemic way, as a network! please contribute

**Comment by yasushisakai** [comment]
what kind of network?

**Comment by jarm0s** [comment]
network of different spaces, like combinin g cafeteria and offices as a co working space

**Comment by yasushisakai** [comment]
I implemented in 84d93ccaf313836b8e870d23c8a4145f826e4a20

**Comment by jarm0s** [comment]
[Kopio serviceID 1.xlsx](https://github.com/CityScope/HelloCityScience/files/2021723/Kopio.serviceID.1.xlsx)

**Comment by mdowneyc** [comment]
Let's make an ice cream city

**Comment by yasushisakai** [comment]
I will incorporate this in the next release!
